//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birimler
    {
        public int ID { get; set; }
        public string BölümAdi { get; set; }
        public int PersonelSayisi { get; set; }
        public string Açıklama { get; set; }
    }
}
