//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPO
    {
        public string URUNADI { get; set; }
        public int STOK { get; set; }
        public int ID { get; set; }
        public string URUNACIKLAMASI { get; set; }
    }
}
