//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DURUM2
    {
        public string BÖLÜM { get; set; }
        public string DOKTORISMI { get; set; }
        public int HASTAKABULSAYISI { get; set; }
        public int IPTALRANDAVUSAYISI { get; set; }
        public int ID { get; set; }
    }
}
