//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TCNO { get; set; }
        public string Anahtar { get; set; }
        public string YETKİ { get; set; }
        public string MAILADRESI { get; set; }
        public string ADRES { get; set; }
        public string TELNO { get; set; }
        public Nullable<System.DateTime> RANDAVUTARIHIGUN { get; set; }
        public Nullable<System.TimeSpan> RANDAVUTARIHISAAT { get; set; }
        public Nullable<int> MuayeneSonucu { get; set; }
    }
}
