//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETE
    {
        public string ILAC { get; set; }
        public System.DateTime TARIH { get; set; }
        public string DOKTOR { get; set; }
        public Nullable<int> RECETENO { get; set; }
        public int ID { get; set; }
        public string HASTA { get; set; }
        public string MAİLADRES { get; set; }
        public string HASTATC { get; set; }
    }
}
